# Generated by Django 5.0.6 on 2026-06-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantprofile',
            name='preferred_county',
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='total_favorites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='total_inquiries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Format: +254...', max_length=15),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='max_distance_km',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Max distance from Pwani University', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='preferred_location_areas',
            field=models.JSONField(blank=True, default=list, help_text='Preferred areas in Kilifi'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='preferred_room_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='student_type',
            field=models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('returning', 'Returning Student'), ('parent', 'Parent Searching')], max_length=20),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='wants_furnished',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='wants_parking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='wants_security',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='wants_wifi',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
