# Generated by Django 5.0.6 on 2026-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_tenantprofile_preferred_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
