# Generated by Django 5.0.6 on 2026-06-09 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproperty',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.county'),
        ),
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property'),
        ),
        migrations.AddField(
            model_name='favoriteproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.amenity'),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.AddField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property'),
        ),
        migrations.AddField(
            model_name='review',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='town',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='properties.county'),
        ),
        migrations.AddField(
            model_name='property',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.town'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['property', 'status'], name='properties__propert_8d7fce_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['tenant'], name='properties__tenant__a75da3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inquiry',
            unique_together={('property', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='favoriteproperty',
            index=models.Index(fields=['tenant'], name='properties__tenant__36e766_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproperty',
            unique_together={('tenant', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='propertyamenity',
            unique_together={('property', 'amenity')},
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'is_primary'], name='properties__propert_6e4e30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyimage',
            unique_together={('property', 'is_primary')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['property', 'is_approved'], name='properties__propert_fccdb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('property', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='town',
            index=models.Index(fields=['slug', 'county'], name='properties__slug_db4ee5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='town',
            unique_together={('name', 'county')},
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['landlord', '-created_at'], name='properties__landlor_db716c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_approved', '-created_at'], name='properties__is_appr_6f3a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['county', 'town'], name='properties__county__dfe25c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties__propert_5c7790_idx'),
        ),
    ]
