# Generated by Django 5.0.6 on 2026-06-10 08:59

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_is_verified_property_verified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary landmark for distance calculations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_popular', models.BooleanField(default=False, help_text='Shows in featured areas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Property Video')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('filters', models.JSONField(help_text='Saved filter criteria as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['category', 'order', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__county__dfe25c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='propertyimage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_landmark_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in km to primary landmark', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text='Featured listing expiry date', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='inquiries_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='category',
            field=models.CharField(choices=[('ROOM', 'Room'), ('COMPOUND', 'Compound/Exterior'), ('BUILDING', 'Building Exterior')], default='ROOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(choices=[('wifi', 'WiFi'), ('parking', 'Parking'), ('water', 'Water Supply'), ('security', 'Security'), ('electricity', 'Electricity'), ('balcony', 'Balcony'), ('furnished', 'Furnished'), ('kitchen', 'Shared Kitchen'), ('laundry', 'Laundry Facility'), ('study_space', 'Study Space')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='propertyamenity',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'category'], name='properties__propert_8c61d9_idx'),
        ),
        migrations.AddIndex(
            model_name='landmark',
            index=models.Index(fields=['is_primary'], name='properties__is_prim_3f66e8_idx'),
        ),
        migrations.AddIndex(
            model_name='locationarea',
            index=models.Index(fields=['slug'], name='properties__slug_6ce4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='locationarea',
            index=models.Index(fields=['is_popular'], name='properties__is_popu_3776e6_idx'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.locationarea'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured', '-created_at'], name='properties__is_feat_7e5c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_verified', '-created_at'], name='properties__is_veri_869486_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['location_area'], name='properties__locatio_b1001e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='properties__latitud_6eb2b0_idx'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propertyvideo',
            index=models.Index(fields=['property'], name='properties__propert_aa5bde_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyvideo',
            constraint=models.CheckConstraint(check=models.Q(('duration_seconds__lte', 60)), name='video_max_60_seconds'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['tenant'], name='properties__tenant__1c3278_idx'),
        ),
    ]
