# Generated by Django 5.0.6 on 2026-06-12 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_landmark_locationarea_propertyvideo_savedsearch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='rent', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('single_room', 'Single Room'), ('bedsitter', 'Bedsitter'), ('studio', 'Studio'), ('1br', '1 Bedroom'), ('2br', '2 Bedrooms'), ('3br', '3 Bedrooms'), ('maisonette', 'Maisonette'), ('commercial', 'Commercial Space'), ('land', 'Land'), ('house_sale', 'House for Sale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
