# Generated by Django 5.0.6 on 2026-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_add_listing_type_and_sale_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/images/'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(upload_to='properties/videos/'),
        ),
    ]
