# Generated by Django 5.0.6 on 2026-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_propertyimage_image_alter_propertyvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
