# Generated by Django 5.0.6 on 2026-06-14 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_propertyimage_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.URLField(max_length=500),
        ),
    ]
