# Generated by Django 5.0.6 on 2026-06-09 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['landlord', 'status'], name='payments_pa_landlor_ebd781_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['property'], name='payments_pa_propert_ac6f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['mpesa_transaction_id'], name='payments_pa_mpesa_t_7ce651_idx'),
        ),
    ]
